Biblioteca.UI/Controllers/LibrosDeBajaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biblioteca.UI.Controllers
{
    public class LibrosDeBajaController : Controller
    {
        // GET: LibrosDeBaja
        public ActionResult Index()
        {
            return View();
        }

        // GET: LibrosDeBaja/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LibrosDeBaja/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LibrosDeBaja/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LibrosDeBaja/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LibrosDeBaja/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LibrosDeBaja/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LibrosDeBaja/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Biblioteca.UI/Controllers/LibrosDisponiblesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biblioteca.UI.Controllers
{
    public class LibrosDisponiblesController : Controller
    {
        // GET: LibrosDisponibles
        public ActionResult Index()
        {
            List<Biblioteca.Model.Libro> laListaDeLibrosDisponibles;
            Biblioteca.Business.GestorDeLibros elGestor = new Business.GestorDeLibros();

            laListaDeLibrosDisponibles = elGestor.ListarLosLibrosDisponiles();

            return View(laListaDeLibrosDisponibles);
        }

        // GET: LibrosDisponibles/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LibrosDisponibles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LibrosDisponibles/Create
        [HttpPost]
        public ActionResult Create(Biblioteca.Model.Libro libro)
        {
            try
            {
                Biblioteca.Business.GestorDeLibros elGestor = new Business.GestorDeLibros();
                elGestor.Agregar(libro);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LibrosDisponibles/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LibrosDisponibles/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LibrosDisponibles/Delete/5
        public ActionResult Prestar(int id)
        {
            Biblioteca.Business.GestorDeLibros elGestor = new Business.GestorDeLibros();
            Biblioteca.Model.Libro elLibro;

            elLibro = elGestor.ObtenerLibroPorId(id);

            return View(elLibro);
        }

        // POST: LibrosDisponibles/Delete/5
        [HttpPost]
        public ActionResult Prestar(Biblioteca.Model.Libro libro)
        {
            try
            {
                Biblioteca.Business.GestorDeLibros elGestor = new Business.GestorDeLibros();
                elGestor.Prestar(libro);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Biblioteca.UI/Controllers/LibrosPrestadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biblioteca.UI.Controllers
{
    public class LibrosPrestadosController : Controller
    {
        // GET: LibrosPrestados
        public ActionResult Index()
        {

            List<Biblioteca.Model.Libro> laListaDeLibrosPrestados;
            Biblioteca.Business.GestorDeLibros elGestor = new Business.GestorDeLibros();

            laListaDeLibrosPrestados = elGestor.ListarLosLibrosPrestados();

            return View(laListaDeLibrosPrestados);
        }

        // GET: LibrosPrestados/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: LibrosPrestados/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LibrosPrestados/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LibrosPrestados/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LibrosPrestados/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LibrosPrestados/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LibrosPrestados/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Biblioteca.UI/Views/LibrosDisponibles/Create.cshtml
@model Biblioteca.Model.Libro

@{
    ViewBag.Title = "Nuevo Libro";
}

<h2>Nuevo Libro</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Libro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Biblioteca.UI/Views/LibrosDisponibles/Index.cshtml
@model IEnumerable<Biblioteca.Model.Libro>

@{
    ViewBag.Title = "Libros Disponibles";
}

<h2>Libros Disponibles</h2>

<p>
    @Html.ActionLink("Nuevo Libro", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Autor)
        </td>
        
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.Id }) |
            @Html.ActionLink("Prestar", "Prestar", new { id=item.Id }) |
            @Html.ActionLink("Dar de Baja", "DarDeBaja", new { id=item.Id })
        </td>
    </tr>
}

</table>

Biblioteca.UI/Views/LibrosDisponibles/Prestar.cshtml
@model Biblioteca.Model.Libro

@{
    ViewBag.Title = "Prestar";
}

<h2>Prestar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Libro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
                        
            @Html.Label("Nombre del cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreCliente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreCliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Biblioteca.UI/Views/LibrosDisponibles/View.cshtml
@model Biblioteca.Model.Libro

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<div>
    <h4>Libro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreCliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreCliente)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Biblioteca.UI/Views/LibrosPrestados/Index.cshtml
@model IEnumerable<Biblioteca.Model.Libro>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        <th>
            @Html.Label("Nombre del Cliente")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Autor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NombreCliente)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>

Biblioteca.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Biblioteca UCR", "Index", "LibrosDisponibles", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Libros Disponibles", "Index", "LibrosDisponibles")</li>
                    <li>@Html.ActionLink("Libros Prestados", "Index", "LibrosPrestados")</li>
                    <li>@Html.ActionLink("Libros de Baja", "Index", "LibrosDeBaja")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Todos los derechos reservados - UCR</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>